alias mkdir="mkdir -p"
alias vim="nvim"
alias k="kubectl"
alias t="tmux"
alias ta="tmux attach -t"
alias tn="tmux new-session -t"
alias tl="tmux list-sessions"
alias npm="bin/npm"
export EDITOR=nvim
export VISUAL=nvim
